---
abstract: 'Check if a string is an email address.'
author:
  - 'John Karr <brainbuz@brainbuz.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-Validator-Email
no_index:
  directory:
    - t
    - inc
requires:
  Email::Address: 1.896
  Email::Valid: 0.19
  Net::DNS: 0.68
  Net::Domain::TLD: 1.69
  Regexp::Common: 2011121001
  String::Validator::Common: 0.97
  Test::More: 0
version: 0.98
